aplikasi/alat/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired


class Input(FlaskForm):
    nm_alat =  StringField('Nama alat', validators=[DataRequired()])
    merk =  StringField('Merk alat', validators=[DataRequired()])
    tipe =  StringField('Tipe alat', validators=[DataRequired()])
    no_seri =  StringField('No Seri', validators=[DataRequired()])
    tgl_kalibrasi = DateField('Tgl. Kalibrasi')  
    aksesoris =  StringField('Aksesoris alat')
    th_pengadaan =  StringField('Tahun pengadaan')
    ket =  StringField('Keterangan')
    simpan = SubmitField('Simpan')


class Edit(FlaskForm):
    nm_alat =  StringField('Nama alat', validators=[DataRequired()])
    merk =  StringField('Merk alat', validators=[DataRequired()])
    tipe =  StringField('Tipe alat', validators=[DataRequired()])
    no_seri =  StringField('No Seri', validators=[DataRequired()])
    tgl_kalibrasi = DateField('Tgl. Kalibrasi')
    aksesoris =  StringField('Aksesoris alat')
    th_pengadaan =  StringField('Tahun pengadaan')
    ket =  StringField('Keterangan')
    edit = SubmitField('Update')

aplikasi/alat/routes.py
from flask import Blueprint, render_template, redirect, url_for, session, flash
from .forms import Input, Edit
from aplikasi import db
from aplikasi.models import Alat, Loguser

mod = Blueprint('alat',__name__, template_folder='templates')


@mod.route('/alat/daftar')
def index():
    if 'username' in session:
        data = {
            'title': 'Data Alat',
            'header' : 'Data Alat Kalibrasi'
        }

        alat = Alat.query.order_by(Alat.id).all()
        return render_template('alat/daftar_alat.html', data=data, alat=alat)
    else:
        return redirect(url_for('user.login'))    


@mod.route('/alat/tambah', methods=['GET','POST'])
def add():
    if 'username' in session:
        data = {
            'title': 'Input Alat',
            'header' : 'Input Alat'
        }

        form = Input()
        if form.validate_on_submit():
            alat = Alat.query.order_by(Alat.id.desc()).first()
            if alat:
                id_number = alat.id + 1
                if len(str(id_number)) < 5:
                    urut = "0" * (5-len(str(id_number))) + str(id_number)
                    kd = f"PK{urut}"
            else:
                id_number = 1
                urut = "0" * (5-1) + str(id_number)
                kd = f"PK{urut}"

            kd_alat = kd
            nm_alat = form.nm_alat.data
            merk = form.merk.data
            tipe = form.tipe.data
            no_seri = form.no_seri.data
            tgl_kalibrasi = form.tgl_kalibrasi.data
            aksesoris = form.aksesoris.data
            th_pengadaan = form.th_pengadaan.data
            ket = form.ket.data

            add_alat = Alat(kd_alat, nm_alat, merk, tipe, no_seri, aksesoris, th_pengadaan, ket, tgl_kalibrasi)
            db.session.add(add_alat)

            aksi = f"input alat:{kd_alat}"

            catatan = Loguser(session['username'], aksi)
            db.session.add(catatan)
            db.session.commit()

            flash('Data sudah disimpan!!','success')
            return redirect(url_for('alat.index'))

        return render_template('alat/tambah_alat.html', data=data, form=form)
    else:
        return redirect(url_for('user.login'))


@mod.route('/alat/<int:id>/edit', methods=['GET','POST'])
def edit(id):
    if 'username' in session:
        data = {
            'title': 'Edit alat',
            'header' : 'Edit alat'
        }

        alat = Alat.query.get_or_404(id)
        if alat:
            form = Edit()
            if form.validate_on_submit():
                alat.nm_alat = form.nm_alat.data
                alat.merk = form.merk.data
                alat.tipe = form.tipe.data
                alat.no_seri = form.no_seri.data
                alat.tgl_kalibrasi = form.tgl_kalibrasi.data
                alat.aksesoris = form.aksesoris.data
                alat.th_pengadaan = form.th_pengadaan.data
                alat.ket = form.ket.data

                aksi = f"edit alat id:{alat.id}"

                catatan = Loguser(session['username'], aksi)
                db.session.add(catatan)

                db.session.commit()
                flash("Data berhasil diupdate!!", "info")
                return redirect(url_for('alat.index'))

            form.nm_alat.data = alat.nm_alat
            form.merk.data = alat.merk
            form.tipe.data = alat.tipe
            form.no_seri.data = alat.no_seri
            form.tgl_kalibrasi.data = alat.tgl_kalibrasi
            form.aksesoris.data = alat.aksesoris
            form.th_pengadaan.data = alat.th_pengadaan
            form.ket.data = alat.ket

            return render_template('alat/edit_alat.html',data=data, form=form)
            
    return redirect(url_for('user.login'))


@mod.route('/alat/<int:id>/hapus', methods=['GET','POST'])
def hapus(id):
    if 'username' in session:
        alat = Alat.query.get_or_404(id)
        if alat:
            db.session.delete(alat)

            aksi = f"hapus alat id:{alat.id}"
            log = Loguser(session['username'], aksi)
            db.session.add(log)

            db.session.commit()
            flash("Data berhaisl dihapus!!", "info")
            return redirect(url_for('alat.index'))
    
    return redirect(url_for('user.login'))

    

aplikasi/user/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from sqlalchemy import exc
from .forms import Register, Edit_user
from aplikasi import db, bcrypt
from aplikasi.models import Users


mod = Blueprint('user',__name__, template_folder='templates')


@mod.route('/login', methods=['GET','POST'])
def login():
    if request.method == "POST":
        user = request.form['username']
        paswd = request.form['password']
        
        u = Users.query.filter_by(username=user).first()
        if u:
            if bcrypt.check_password_hash(u.password, paswd):
                session['username'] = user
                session['nm_lengkap'] = u.nm_lengkap
                session['level'] = u.level
                return redirect(url_for('main.index'))
            else:
                flash('Password anda salah!!', 'warning')
                return redirect(url_for('user.login'))

        flash('Username tidak ditemukan!!','info')
        return redirect(url_for('user.login'))
        
    return render_template('user/login.html')


@mod.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('user.login'))


@mod.route('/user/list')
def list():
    data = {
        'title':'Users list',
        'header':'Users list',
        'user' : Users.query.all()
    }

    return render_template('user/index.html', data=data)


@mod.route('/user/add', methods=['GET','POST'])
def reg():
    data = {
        'title':'Add user',
        'header':'Add user'
    }

    form = Register()
    if form.validate_on_submit():
        try:
            username = form.username.data
            pw_hash = bcrypt.generate_password_hash(form.password.data)
            email = form.email.data
            nm_lengkap = form.nm_lengkap.data
            level = form.level.data
            pwdnew = pw_hash.decode("utf-8", "ignore")

            user = Users(username, pwdnew, email, nm_lengkap,level, "")
            db.session.add(user)
            db.session.commit()
            flash('User baru berhasil dibuat!!','success')
            return redirect(url_for('user.list')) 
        except exc.IntegrityError:
            db.session.rollback()
            flash('Maaf, data sudah ada !!!. Silahkan gunakan yang lain.','warning')
            return redirect(url_for('user.reg'))        

    return render_template('user/register.html', data=data, form=form)

@mod.route('/user/edit/<int:id>', methods=['GET','POST'])
def edit(id):
    data = {
        'title':'Edit user',
        'header':'Edit user'
    }
    user = Users.query.get_or_404(id)

    if user:
        form = Edit_user()
        if form.validate_on_submit():
            user.username = form.username.data
            user.email = form.email.data
            user.nm_lengkap = form.nm_lengkap.data
            user.level = form.level.data
            
            db.session.commit()

            flash("User berhasil diupdate!","info")
            return redirect(url_for('user.list'))
        
        form.username.data = user.username
        form.email.data = user.email
        form.nm_lengkap.data = user.nm_lengkap
        form.level.data = user.level

        return render_template('user/edit.html', data=data, form=form)

    
@mod.route('/user/hapus/<int:id>', methods=['GET','POST'])
def hapus(id):
    user = Users.query.get_or_404(id)
    if user:
        db.session.delete(user)
        db.session.commit()

        flash("Data berhasil dihapus!!","info")
        return redirect(url_for('user.list'))

aplikasi/templates/alat/base_alat.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{{ data.title }} · SIMUPF</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Bootstrap dataTables -->
    <link href="{{ url_for('static', filename='/dataTables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">

    <!-- sweetalert -->
    <script src="{{ url_for('static', filename='sweetalert.min.js') }}"></script>

  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{{ url_for('main.dashboard') }}"><span><img src="{{ url_for('static', filename='favicon.png') }}" alt=""></span> UPFK Palembang</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{{ url_for('user.logout') }}"><span data-feather="log-out"></span> Logout</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.dashboard') }}">
              <span data-feather="arrow-left-circle"></span>
              Kembali 
              <!-- <span class="sr-only">(current)</span> -->
            </a>
          </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Menu alat</span>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('alat.index') }}">
              <span data-feather="file-text"></span>
              Data Alat
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('alat.add') }}">
              <span data-feather="folder-plus"></span>
              Input Alat
            </a>
          </li>
        </ul>
      </div>
    </nav>

    {% block content %}
    {% endblock %}
  </div>
</div>
      <script src="{{ url_for('static', filename='jquery-3.5.1.slim.min.js') }}"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
      <script src="{{ url_for('static', filename='/dist/js/bootstrap.bundle.min.js') }}"></script>
      <script src="{{ url_for('static', filename='feather.min.js') }}"></script>
      <script src="{{ url_for('static', filename='Chart.min.js') }}"></script>
      <script src="{{ url_for('static', filename='dashboard.js') }}"></script>
      <script src="{{ url_for('static', filename='/dataTables/jquery.dataTables.min.js') }}"></script>
      <script src="{{ url_for('static', filename='/dataTables/dataTables.bootstrap4.min.js') }}"></script>
      <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
      </script>

  </body>
</html>

aplikasi/templates/alat/daftar_alat.html
{% extends 'alat/base_alat.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">{{ data.header }}</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
          <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
      </div>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}      
        {% for category,message in messages %}
        <!-- <div class="alert alert-{{ category }} alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{message}}
        </div> -->
        <script>
          swal("Notifikasi", "{{message}}", "{{ category }}");
        </script>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="table-responsive">
      <table id="table_id" class="table table-striped table-sm">
        <thead>
          <tr>
            <th>No</th>
            <th>Kode Alat</th>
            <th>Nama</th>
            <th>Merk</th>
            <th>Tipe</th>
            <th>No. Seri</th>
            <th>Tgl. Kalibrasi</th>
            <th>Aksesori</th>
            <th>Pengadaan</th>
            <th>Keterangan</th>
            <th>Aksi</th>
          </tr>
        </thead>
        <tbody>
          {% for d in alat %}
          <tr>
            <td>{{ loop.index }}</td>
            <td>{{ d.kd_alat }}</td>
            <td>{{ d.nm_alat }}</td>
            <td>{{ d.merk }}</td>
            <td>{{ d.tipe }}</td>
            <td>{{ d.no_seri }}</td>
            <td>{{ d.tgl_kalibrasi }}</td>
            <td>{{ d.aksesoris }}</td>
            <td>{{ d.th_pengadaan }}</td>
            <td>{{ d.ket }}</td>
            <td><a href="{{ url_for('alat.edit',id=d.id) }}" title="edit"><span data-feather="edit"></span></a> | <a href="" title="hapus" data-toggle="modal" data-target="#hapus{{ d.id }}"><span data-feather="trash-2" ></span></a></td>
          </tr>

          <!-- Modal Konfirmasi Hapus-->
          <div class="modal fade" id="hapus{{ d.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <strong>Anda yakin akan menghapus {{ d.nm_alat }}?</strong>
                </div>
                <div class="modal-footer">
                  <form action="{{ url_for('alat.hapus',id=d.id) }}" method="post">
                    <button type="submit" class="btn btn-primary">Iya</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                  </form>                 
                </div>
              </div>
            </div>
          </div> 

          {% endfor %}                    
        </tbody>
      </table>
    </div>
</main>
{% endblock %}

aplikasi/templates/alat/edit_alat.html
{% extends 'alat/base_alat.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">{{ data.header }}</h1>
    </div>
  
    <form method="POST" novalidate>
      {{ form.hidden_tag() }}

      <div class="form-group row">
        {{ form.nm_alat.label(class="col-sm-2 col-form-label") }}
        {% if form.nm_alat.errors %}
          <div class="col-sm-10 has-error">
            {{ form.nm_alat(class="form-control") }}                                        
            {% for error in form.nm_alat.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.nm_alat(class="form-control")}}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.merk.label(class="col-sm-2 col-form-label") }}
        {% if form.merk.errors %}
          <div class="col-sm-10 has-error">
            {{ form.merk(class="form-control") }}                                        
            {% for error in form.merk.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.merk(class="form-control")}}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.tipe.label(class="col-sm-2 col-form-label") }}
        {% if form.tipe.errors %}
          <div class="col-sm-10 has-error">
            {{ form.tipe(class="form-control") }}                                        
            {% for error in form.tipe.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.tipe(class="form-control")}}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.no_seri.label(class="col-sm-2 col-form-label") }}
        {% if form.no_seri.errors %}
          <div class="col-sm-10 has-error">
            {{ form.no_seri(class="form-control") }}                                        
            {% for error in form.no_seri.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.no_seri(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.tgl_kalibrasi.label(class="col-sm-2 col-form-label") }}
        {% if form.tgl_kalibrasi.errors %}
          <div class="col-sm-10 has-error">
            {{ form.tgl_kalibrasi(class="form-control") }}                                        
            {% for error in form.tgl_kalibrasi.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.tgl_kalibrasi(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.aksesoris.label(class="col-sm-2 col-form-label") }}
        {% if form.aksesoris.errors %}
          <div class="col-sm-10 has-error">
            {{ form.aksesoris(class="form-control") }}                                        
            {% for error in form.aksesoris.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.aksesoris(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.th_pengadaan.label(class="col-sm-2 col-form-label") }}
        {% if form.th_pengadaan.errors %}
          <div class="col-sm-10 has-error">
            {{ form.th_pengadaan(class="form-control") }}                                        
            {% for error in form.th_pengadaan.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.th_pengadaan(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.ket.label(class="col-sm-2 col-form-label") }}
        {% if form.ket.errors %}
          <div class="col-sm-10 has-error">
            {{ form.ket(class="form-control") }}                                        
            {% for error in form.ket.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.ket(class="form-control") }}
        </div>
        {% endif %}
      </div>

        <div class="form-group row">
          <div class="col-sm-10">
            {{ form.edit(class="btn btn-primary") }}
          </div>
        </div>
      </form>
</main>
{% endblock %}

aplikasi/templates/alat/tambah_alat.html
{% extends 'alat/base_alat.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">{{ data.header }}</h1>
    </div>
  
    <form method="POST" novalidate>
      {{ form.hidden_tag() }}

      <div class="form-group row">
        {{ form.nm_alat.label(class="col-sm-2 col-form-label") }}
        {% if form.nm_alat.errors %}
          <div class="col-sm-10 has-error">
            {{ form.nm_alat(class="form-control") }}                                        
            {% for error in form.nm_alat.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.nm_alat(class="form-control", placeholder='Nama alat') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.merk.label(class="col-sm-2 col-form-label") }}
        {% if form.merk.errors %}
          <div class="col-sm-10 has-error">
            {{ form.merk(class="form-control") }}                                        
            {% for error in form.merk.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.merk(class="form-control", placeholder='Merk alat') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.tipe.label(class="col-sm-2 col-form-label") }}
        {% if form.tipe.errors %}
          <div class="col-sm-10 has-error">
            {{ form.tipe(class="form-control") }}                                        
            {% for error in form.tipe.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.tipe(class="form-control", placeholder='Tipe alat') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.no_seri.label(class="col-sm-2 col-form-label") }}
        {% if form.no_seri.errors %}
          <div class="col-sm-10 has-error">
            {{ form.no_seri(class="form-control") }}                                        
            {% for error in form.no_seri.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.no_seri(class="form-control", placeholder='No seri') }}
        </div>
        {% endif %}
      </div>
       <div class="form-group row">
        {{ form.no_seri.label(class="col-sm-2 col-form-label") }}
        {% if form.no_seri.errors %}
          <div class="col-sm-10 has-error">
            {{ form.no_seri(class="form-control") }}                                        
            {% for error in form.no_seri.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.no_seri(class="form-control", placeholder='No seri') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.tgl_kalibrasi.label(class="col-sm-2 col-form-label") }}
        {% if form.tgl_kalibrasi.errors %}
          <div class="col-sm-10 has-error">
            {{ form.tgl_kalibrasi(class="form-control") }}                                        
            {% for error in form.tgl_kalibrasi.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.tgl_kalibrasi(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.aksesoris.label(class="col-sm-2 col-form-label") }}
        {% if form.aksesoris.errors %}
          <div class="col-sm-10 has-error">
            {{ form.aksesoris(class="form-control") }}                                        
            {% for error in form.aksesoris.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.aksesoris(class="form-control", placeholder='Aksesoris') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.th_pengadaan.label(class="col-sm-2 col-form-label") }}
        {% if form.th_pengadaan.errors %}
          <div class="col-sm-10 has-error">
            {{ form.th_pengadaan(class="form-control") }}                                        
            {% for error in form.th_pengadaan.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.th_pengadaan(class="form-control", placeholder='contoh: 2011') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.ket.label(class="col-sm-2 col-form-label") }}
        {% if form.ket.errors %}
          <div class="col-sm-10 has-error">
            {{ form.ket(class="form-control") }}                                        
            {% for error in form.ket.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.ket(class="form-control", placeholder='Keterangan') }}
        </div>
        {% endif %}
      </div>

        <div class="form-group row">
          <div class="col-sm-10">
            {{ form.simpan(class="btn btn-primary") }}
          </div>
        </div>
      </form>
</main>
{% endblock %}