aplikasi/fasyankes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField
from wtforms.validators import DataRequired, Email


class Input(FlaskForm):
    nama =  StringField('Nama Fasyankes', validators=[DataRequired()])
    status =  SelectField('Status', 
        choices=[('none','--Pilihan--'),('Perusahaan','Perusahaan'),('Klinik','Klinik'),
        ('Laboratorium','Laboratorium'),('Kementerian','Kementerian'),('Instansi Pemerintah','Instansi Pemerintah'),('RS. Pemerintah','RS. Pemerintah'),('RS. Swasta','RS. Swasta'),
        ('Puskesmas','Puskesmas')])
    alamat = StringField("Alamat", validators=[DataRequired()])
    kota = StringField("Kota", validators=[DataRequired()])
    provinsi = StringField("Provinsi", validators=[DataRequired()])
    email = StringField("Email",validators=[DataRequired(), Email()])
    telepon = StringField("Telepon", validators=[DataRequired()])
    fax = StringField("Fax")
    simpan = SubmitField('Simpan')


class Edit(FlaskForm):
    nama =  StringField('Nama Fasyankes', validators=[DataRequired()])
    status =  SelectField('Status', 
        choices=[('none','--Pilihan--'),('Perusahaan','Perusahaan'),('Klinik','Klinik'),
        ('Laboratorium','Laboratorium'),('Kementerian','Kementerian'),('Instansi Pemerintah','Instansi Pemerintah'),('RS. Pemerintah','RS. Pemerintah'),('RS. Swasta','RS. Swasta'),
        ('Puskesmas','Puskesmas')])
    alamat = StringField("Alamat", validators=[DataRequired()])
    kota = StringField("Kota", validators=[DataRequired()])
    provinsi = StringField("Provinsi", validators=[DataRequired()])
    email = StringField("Email",validators=[DataRequired(), Email()])
    telepon = StringField("Telepon", validators=[DataRequired()])
    fax = StringField("Fax")
    update = SubmitField('Update')

aplikasi/fasyankes/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from aplikasi import db
from aplikasi.models import Fasyankes, Loguser
from .forms import Input, Edit


mod = Blueprint('fasyankes',__name__, template_folder='templates')


@mod.route('/fasyankes')
def index():
    if 'username' in session:
        data = {'title':'Data Fasyankes',
            'header':'Data Fasyankes',
            'fasyankes': Fasyankes.query.all()
            }

        return render_template('fasyankes/index.html', data=data)
    
    return redirect(url_for('user.login'))


@mod.route('/fasyankes/input', methods=['GET','POST'])
def input():
    if 'username' in session:
        data = {'title':'Input Fasyankes',
            'header':'Input Fasyankes'
            }

        form=Input()
        if form.validate_on_submit():            
            nama = form.nama.data
            status = form.status.data
            alamat = form.alamat.data
            kota = form.kota.data
            provinsi = form.provinsi.data
            email = form.email.data
            telepon = form.telepon.data
            fax = form.fax.data
            
            # input data ke dalam table fasyankes
            add_fasyankes = Fasyankes(nama, status, alamat, kota, provinsi, email, telepon, fax)
            db.session.add(add_fasyankes)
            
            # flush data fasyankes sebelum commit
            db.session.flush()

            aksi = f"add fasyankes: {add_fasyankes.id}"
            log = Loguser(session['username'], aksi)
            db.session.add(log)
            # commit data add fasyankes dan loguser
            db.session.commit()

            flash('Data berhasil disimpan!!!','success')
            return redirect(url_for('fasyankes.index'))
            
        return render_template('fasyankes/input.html', data=data, form=form)
    
    return redirect(url_for('user.login'))


@mod.route('/fasyankes/<int:id>/edit', methods=['GET','POST'])
def edit(id):
    if 'username' in session:
        data = {'title':'Edit data',
            'header':'Edit data'
            }
        cari = Fasyankes.query.get_or_404(id)

        form = Edit()
        if form.validate_on_submit():
            cari.nama = form.nama.data
            cari.status = form.status.data
            cari.alamat = form.alamat.data
            cari.kota = form.kota.data
            cari.provinsi = form.provinsi.data
            cari.email = form.email.data
            cari.telepon = form.telepon.data
            cari.fax = form.fax.data

            aksi = f"fasyankes edit: {cari.id}"
            log = Loguser(session['username'], aksi)
            db.session.add(log)
            db.session.commit()

            flash('Data berhasil diupdate!!','success')
            return redirect(url_for('fasyankes.index'))

        form.nama.data = cari.nama
        form.status.data = cari.status
        form.alamat.data = cari.alamat
        form.kota.data = cari.kota
        form.provinsi.data = cari.provinsi
        form.email.data = cari.email
        form.telepon.data = cari.telepon
        form.fax.data = cari.fax

        return render_template('fasyankes/edit.html', data=data, form=form)

    return redirect(url_for('user.login'))


@mod.route('/fasyankes/<int:id>/hapus', methods=['GET','POST'])
def hapus(id):
    if 'username' in session:
        f = Fasyankes.query.get_or_404(id)
        if f:
            db.session.delete(f)

            aksi = f"fasyankes del:{f.nama}"
            log = Loguser(session['username'], aksi)
            db.session.add(log)
            db.session.commit()

            flash('Data telah terhapus !!','warning')
            return redirect(url_for('fasyankes.index'))
    
    return redirect(url_for('user.login'))

aplikasi/user/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from sqlalchemy import exc
from .forms import Register, Edit_user
from aplikasi import db, bcrypt
from aplikasi.models import Users


mod = Blueprint('user',__name__, template_folder='templates')


@mod.route('/login', methods=['GET','POST'])
def login():
    if request.method == "POST":
        user = request.form['username']
        paswd = request.form['password']
        
        u = Users.query.filter_by(username=user).first()
        if u:
            if bcrypt.check_password_hash(u.password, paswd):
                session['username'] = user
                session['nm_lengkap'] = u.nm_lengkap
                session['level'] = u.level
                return redirect(url_for('main.index'))
            else:
                flash('Password anda salah!!', 'warning')
                return redirect(url_for('user.login'))

        flash('Username tidak ditemukan!!','info')
        return redirect(url_for('user.login'))
        
    return render_template('user/login.html')


@mod.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('user.login'))


@mod.route('/user/list')
def list():
    data = {
        'title':'Users list',
        'header':'Users list',
        'user' : Users.query.all()
    }

    return render_template('user/index.html', data=data)


@mod.route('/user/add', methods=['GET','POST'])
def reg():
    data = {
        'title':'Add user',
        'header':'Add user'
    }

    form = Register()
    if form.validate_on_submit():
        try:
            username = form.username.data
            pw_hash = bcrypt.generate_password_hash(form.password.data)
            email = form.email.data
            nm_lengkap = form.nm_lengkap.data
            level = form.level.data
            pwdnew = pw_hash.decode("utf-8", "ignore")

            user = Users(username, pwdnew, email, nm_lengkap,level, "")
            db.session.add(user)
            db.session.commit()
            flash('User baru berhasil dibuat!!','success')
            return redirect(url_for('user.list')) 
        except exc.IntegrityError:
            db.session.rollback()
            flash('Maaf, data sudah ada !!!. Silahkan gunakan yang lain.','warning')
            return redirect(url_for('user.reg'))        

    return render_template('user/register.html', data=data, form=form)

@mod.route('/user/edit/<int:id>', methods=['GET','POST'])
def edit(id):
    data = {
        'title':'Edit user',
        'header':'Edit user'
    }
    user = Users.query.get_or_404(id)

    if user:
        form = Edit_user()
        if form.validate_on_submit():
            user.username = form.username.data
            user.email = form.email.data
            user.nm_lengkap = form.nm_lengkap.data
            user.level = form.level.data
            
            db.session.commit()

            flash("User berhasil diupdate!","info")
            return redirect(url_for('user.list'))
        
        form.username.data = user.username
        form.email.data = user.email
        form.nm_lengkap.data = user.nm_lengkap
        form.level.data = user.level

        return render_template('user/edit.html', data=data, form=form)

    
@mod.route('/user/hapus/<int:id>', methods=['GET','POST'])
def hapus(id):
    user = Users.query.get_or_404(id)
    if user:
        db.session.delete(user)
        db.session.commit()

        flash("Data berhasil dihapus!!","info")
        return redirect(url_for('user.list'))

aplikasi/templates/fasyankes/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{{ data.title }} · SIMUPF</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Bootstrap dataTables -->
    <link href="{{ url_for('static', filename='/dataTables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">

    <!-- sweetalert -->
    <script src="{{ url_for('static', filename='sweetalert.min.js') }}"></script>

  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{{ url_for('main.dashboard') }}"><span><img src="{{ url_for('static', filename='favicon.png') }}" alt=""></span> UPFK Palembang</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{{ url_for('user.logout') }}"><span data-feather="log-out"></span> Logout</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.dashboard') }}">
              <span data-feather="arrow-left-circle"></span>
              Kembali 
              <!-- <span class="sr-only">(current)</span> -->
            </a>
          </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Menu</span>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('fasyankes.index') }}">
              <span data-feather="file-text"></span>
              Data Fasyankes
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('fasyankes.input') }}">
              <span data-feather="folder-plus"></span>
              Input Fasyankes
            </a>
          </li>
        </ul>
      </div>
    </nav>

    {% block content %}
    {% endblock %}
  </div>
</div>
      <script src="{{ url_for('static', filename='jquery-3.5.1.slim.min.js') }}"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
      <script src="{{ url_for('static', filename='/dist/js/bootstrap.bundle.min.js') }}"></script>
      <script src="{{ url_for('static', filename='feather.min.js') }}"></script>
      <script src="{{ url_for('static', filename='Chart.min.js') }}"></script>
      <script src="{{ url_for('static', filename='dashboard.js') }}"></script>
      <script src="{{ url_for('static', filename='/dataTables/jquery.dataTables.min.js') }}"></script>
      <script src="{{ url_for('static', filename='/dataTables/dataTables.bootstrap4.min.js') }}"></script>
      <script>
        $(document).ready( function () {
            $('#working').DataTable();
        } );
      </script>

  </body>
</html>

aplikasi/templates/fasyankes/edit.html
{% extends 'fasyankes/base.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">{{ data.header }}</h1>
    </div>
  
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}      
            {% for category,message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{message}}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form method="POST" novalidate>
      {{ form.hidden_tag() }}

      <div class="form-group row">
        {{ form.nama.label(class="col-sm-2 col-form-label") }}
        {% if form.nama.errors %}
          <div class="col-sm-10 has-error">
            {{ form.nama(class="form-control") }}                                        
            {% for error in form.nama.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.nama(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.status.label(class="col-sm-2 col-form-label") }}
        {% if form.status.errors %}
          <div class="col-sm-10 has-error">
            {{ form.status(class="form-control") }}                                        
            {% for error in form.status.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.status(class="form-control")}}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.alamat.label(class="col-sm-2 col-form-label") }}
        {% if form.alamat.errors %}
          <div class="col-sm-10 has-error">
            {{ form.alamat(class="form-control") }}                                        
            {% for error in form.alamat.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.alamat(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.kota.label(class="col-sm-2 col-form-label") }}
        {% if form.kota.errors %}
          <div class="col-sm-10 has-error">
            {{ form.kota(class="form-control") }}                                        
            {% for error in form.kota.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.kota(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.provinsi.label(class="col-sm-2 col-form-label") }}
        {% if form.provinsi.errors %}
          <div class="col-sm-10 has-error">
            {{ form.provinsi(class="form-control") }}                                        
            {% for error in form.provinsi.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.provinsi(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.email.label(class="col-sm-2 col-form-label") }}
        {% if form.email.errors %}
          <div class="col-sm-10 has-error">
            {{ form.email(class="form-control") }}                                        
            {% for error in form.email.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.email(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.telepon.label(class="col-sm-2 col-form-label") }}
        {% if form.telepon.errors %}
          <div class="col-sm-10 has-error">
            {{ form.telepon(class="form-control") }}                                        
            {% for error in form.telepon.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.telepon(class="form-control") }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.fax.label(class="col-sm-2 col-form-label") }}
        {% if form.fax.errors %}
          <div class="col-sm-10 has-error">
            {{ form.fax(class="form-control") }}                                        
            {% for error in form.fax.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.fax(class="form-control") }}
        </div>
        {% endif %}
      </div>

        <div class="form-group row">
          <div class="col-sm-10">
            {{ form.update(class="btn btn-primary") }}
          </div>
        </div>
      </form>
</main>
{% endblock %}

aplikasi/templates/fasyankes/index.html
{% extends 'fasyankes/base.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ data.header }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
    </div>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}      
      {% for category,message in messages %}
      <script>
        swal("Notifikasi", "{{message}}", "{{ category }}");
      </script>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div class="table-responsive">
    <table id="working" class="table table-striped table-sm">
      <thead>
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Status</th>
          <th>Alamat</th>
          <th>Kota</th>
          <th>Provinsi</th>
          <th>Email</th>
          <th>Telepon</th>
          <th>Fax</th>
          <th>Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for d in data.fasyankes %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ d.nama }}</td>
          <td>{{ d.status }}</td>
          <td>{{ d.alamat }}</td>
          <td>{{ d.kota }}</td>
          <td>{{ d.provinsi }}</td>
          <td>{{ d.email }}</td>
          <td>{{ d.telepon }}</td>
          <td>{{ d.fax }}</td>
          <td><a href="{{ url_for('fasyankes.edit',id=d.id) }}" title="Edit"><span data-feather="edit"></span></a> | <a href="" data-toggle="modal" data-target="#hapus{{ d.id }}" title="Hapus"><span data-feather="trash-2"></span></a></td>
        </tr>

        <!-- Modal Konfirmasi Hapus-->
        <div class="modal fade" id="hapus{{ d.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <strong>Anda yakin akan menghapus {{ d.nama }}?</strong>
              </div>
              <div class="modal-footer">
                <form action="{{ url_for('fasyankes.hapus',id=d.id) }}" method="post">
                  <button type="submit" class="btn btn-primary">Iya</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                </form>                 
              </div>
            </div>
          </div>
        </div>        
        {% endfor %}       
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

aplikasi/templates/fasyankes/input.html
{% extends 'fasyankes/base.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">{{ data.header }}</h1>
    </div>
  
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}      
            {% for category,message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{message}}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form method="POST" novalidate>
      {{ form.hidden_tag() }}

      <div class="form-group row">
        {{ form.nama.label(class="col-sm-2 col-form-label") }}
        {% if form.nama.errors %}
          <div class="col-sm-10 has-error">
            {{ form.nama(class="form-control") }}                                        
            {% for error in form.nama.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.nama(class="form-control", placeholder='Nama fasyankes') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.status.label(class="col-sm-2 col-form-label") }}
        {% if form.status.errors %}
          <div class="col-sm-10 has-error">
            {{ form.status(class="form-control") }}                                        
            {% for error in form.status.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.status(class="form-control")}}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.alamat.label(class="col-sm-2 col-form-label") }}
        {% if form.alamat.errors %}
          <div class="col-sm-10 has-error">
            {{ form.alamat(class="form-control") }}                                        
            {% for error in form.alamat.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.alamat(class="form-control", placeholder='Alamat') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.kota.label(class="col-sm-2 col-form-label") }}
        {% if form.kota.errors %}
          <div class="col-sm-10 has-error">
            {{ form.kota(class="form-control") }}                                        
            {% for error in form.kota.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.kota(class="form-control", placeholder='Nama Kota') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.provinsi.label(class="col-sm-2 col-form-label") }}
        {% if form.provinsi.errors %}
          <div class="col-sm-10 has-error">
            {{ form.provinsi(class="form-control") }}                                        
            {% for error in form.provinsi.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.provinsi(class="form-control", placeholder='Provinsi') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.email.label(class="col-sm-2 col-form-label") }}
        {% if form.email.errors %}
          <div class="col-sm-10 has-error">
            {{ form.email(class="form-control") }}                                        
            {% for error in form.email.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.email(class="form-control", placeholder='Email') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.telepon.label(class="col-sm-2 col-form-label") }}
        {% if form.telepon.errors %}
          <div class="col-sm-10 has-error">
            {{ form.telepon(class="form-control") }}                                        
            {% for error in form.telepon.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.telepon(class="form-control", placeholder='Telepon') }}
        </div>
        {% endif %}
      </div>

      <div class="form-group row">
        {{ form.fax.label(class="col-sm-2 col-form-label") }}
        {% if form.fax.errors %}
          <div class="col-sm-10 has-error">
            {{ form.fax(class="form-control") }}                                        
            {% for error in form.fax.errors  %}
                <span class="control-label">{{ error }}</span>
            {% endfor %}
          </div>
        {% else %}
        <div class="col-sm-10">
          {{ form.fax(class="form-control", placeholder='No. Fax') }}
        </div>
        {% endif %}
      </div>

        <div class="form-group row">
          <div class="col-sm-10">
            {{ form.simpan(class="btn btn-primary") }}
          </div>
        </div>
      </form>
</main>
{% endblock %}