aplikasi/pinjam/forms.py
from flask_wtf import FlaskForm
from sqlalchemy import values
from wtforms import StringField, SubmitField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired
from wtforms_sqlalchemy.fields import QuerySelectField
from aplikasi.models import Fasyankes


def pilih_fasyankes():
    return Fasyankes.query

class Input(FlaskForm):    
    peminjam_alat =  SelectField('Peminjam Alat',
        choices=[('none','...Pilih..'),('Andi P','Andi Purba'),('Azizil T','Azizil Tiara Putra'),('M Agung','M Agung S'),('M Ilham','M Ilham Maulana'),('Sandra M','Sandra Monika'),('Demtania','Demtania'),('Robiyansyah','Robiyansyah'),('Elvira','Elvira'), ('Hendro','Hendro')])    
    tujuan = QuerySelectField(query_factory=pilih_fasyankes, allow_blank=True, get_label='nama')
    tanggal_berangkat = DateField('Tanggal Keberangkatan', validators=[DataRequired()])  
    tanggal_kembali = DateField('Tanggal Kembali', validators=[DataRequired()])  
    keterangan = StringField("Keterangan", validators="")
    simpan = SubmitField('Lanjut')

class Form_add_alat(FlaskForm):
    kd_alat =  StringField('Kode Alat', validators=[DataRequired()])
    simpan = SubmitField('Simpan')

aplikasi/pinjam/routes.py
from flask import Blueprint, jsonify, render_template, redirect, url_for, session, flash, request
from aplikasi import db
from aplikasi.models import Log_pinjam, Peminjam_alat, Fasyankes, Loguser, Alat
from .forms import Input, Form_add_alat
from datetime import datetime

mod = Blueprint('pinjam',__name__, template_folder='templates')


@mod.route('/pinjam', methods=['GET'])
def index():
    if 'username' in session:
        data = {
            'title': 'Data Peminjaman',
            'header' : 'Data Peminjaman',
            'pinjam': Peminjam_alat.query.order_by(Peminjam_alat.tanggal.desc()).limit(50).all()
        }
        return render_template('pinjam/index.html', data=data)
    
    return redirect(url_for('user.login'))


@mod.route('/pinjam/input', methods=['GET','POST'])
def input():
    if 'username' in session:
        data = {
            'title': 'Input Peminjaman',
            'header' : 'Input Peminjaman'
        }
        form = Input()
        form.tujuan.query = Fasyankes.query.order_by(Fasyankes.nama).all()

        if form.validate_on_submit():
            peminjam_alat = form.peminjam_alat.data
            petugas_catat = session.get('nm_lengkap')
            # tanggal = form.tanggal.data
            status = 'Input'
            tujuan = str(form.tujuan.data)
            tanggal_berangkat = form.tanggal_berangkat.data
            tanggal_kembali = form.tanggal_kembali.data
            keterangan = form.keterangan.data

            if peminjam_alat != session.get('nm_lengkap'):
                # status input untuk proses yang belum selesai, submit untuk proses yang sudah selesai
                pinjam = Peminjam_alat(peminjam_alat,petugas_catat, status, tujuan, tanggal_berangkat,tanggal_kembali, keterangan)
                db.session.add(pinjam)
                db.session.commit()

                return redirect(url_for('pinjam.daftar',id=pinjam.id))
            else:
                flash("Maaf petugas catat tidak boleh meminjam !!!", "error")
                return redirect(url_for('pinjam.input'))

        return render_template('pinjam/input.html', data=data, form=form)
    
    return redirect(url_for('user.login'))


@mod.route('/pinjam/input/<int:id>', methods=['GET','POST'])
def daftar(id):
    if 'username' in session:
        data = {
            'title': 'Daftar peminjaman',
            'header' : 'Daftar Peminjaman',
            'query' : Peminjam_alat.query.get_or_404(id)
        }

        form = Form_add_alat()
        if form.validate_on_submit():
            kd_alat = form.kd_alat.data
            # mencari id kode alat
            alat = Alat.query.filter_by(kd_alat=kd_alat).first()
            if alat:
                # FILTER ALAT TIDAK BOLEH SAMA PADA 1 PEMINJAM
                rangkap = 0
                cari = Log_pinjam.query.filter_by(id_peminjam=id).all()
                for i in cari:
                    if i.id_alat == alat.id:
                        rangkap = 1

                if rangkap==0:
                    qlog = Log_pinjam(alat.id, id,"","")
                    db.session.add(qlog)
                    db.session.commit()
                    flash('Data berhasil ditambahkan..','success')
                else:
                    flash('Maaf, Data sudah ada!','danger')
                                
                return redirect(url_for('pinjam.daftar', id=id))

        detail = Log_pinjam.query.filter_by(id_peminjam=id).all()
        return render_template('pinjam/input_alat.html', data=data, detail=detail, form=form)
    return redirect(url_for('user.login'))

@mod.route('/pinjam/inputalat/<int:id>', methods=['GET','POST'])
def inputalat(id):
    if request.method == "POST":
        id_alat = request.form['hasil']        
        id_peminjam = id

        print(f'{id_alat} and {id_peminjam}')

        q = Log_pinjam(id_alat, id_peminjam,"")
        db.session.add(q)
        db.session.commit()
        flash('Data berhasil ditambahkan!','success')

        detail = Log_pinjam.query.filter_by(id_peminjam=id_peminjam).all()
        
    return jsonify({'htmlresponse': render_template('pinjam/response.html', detail=detail )})


@mod.route('/pinjam/<int:id>/hapus', methods=['GET','POST'])
def hapus(id):
    if 'username' in session:
        pinjam = Peminjam_alat.query.get(id)
        if pinjam:
            db.session.delete(pinjam)

        logpinjam = Log_pinjam.query.filter_by(id_peminjam=id).all()
        if logpinjam:               
            # hapus id diatas pada table Peminjaman_alat dan Log_pinjam
            db.session.delete(logpinjam)            
               
            
        aksi = f"menghapus peminjaman alat id:{pinjam.id}"
        log = Loguser(session['username'], aksi)
        db.session.add(log)

        db.session.commit()
        flash("Data berhasil dihapus!!", "info")
        return redirect(url_for('pinjam.index'))

    return redirect(url_for('user.login'))


@mod.route('/pinjam/lihat_data/<int:id>')
def lihat_data(id):
    if 'username' in session:
        data = {
            'title' : 'Daftar Pinjam Alat',
            'header' :'Daftar Pinjam Alat'
        }
        peminjam = Peminjam_alat.query.get(id)
        lihat = Log_pinjam.query.filter_by(id_peminjam=id).all()
        return render_template('pinjam/daftar_pinjam.html', data=data, lihat=lihat, peminjam=peminjam)
    return redirect(url_for('user.login'))


@mod.route('/pinjam/hapus_alat/<int:id>', methods=['GET','POST'])
def hapus_alat(id):
    if "username" in session:
        # cek id pada table
        clog = Log_pinjam.query.get_or_404(id)
        if clog:
            nm_alat= clog.alat.nm_alat
            id_peminjam = clog.id_peminjam
            db.session.delete(clog)

            aksi = f"hapus peminjaman alat:{nm_alat}"
            log = Loguser(session['username'], aksi)
            db.session.add(log)

            # eksekusi query
            db.session.commit()
            flash(f'Alat {clog.alat.nm_alat} berhasil dihapus!!','info')
            return redirect(url_for('pinjam.daftar', id=id_peminjam))
    return redirect(url_for('user.login'))


@mod.route('/pinjam/simpan_proses/<int:id>', methods=['GET','POST'])
def simpan_proses(id):
    if "username" in session:
        pinjam = Peminjam_alat.query.get_or_404(id)
        if pinjam:
            pinjam.status ='Pinjam'

            aksi = f"Pinjam alat: {pinjam.id} simpan"
            log = Loguser(session['username'], aksi)
            db.session.add(log)
            db.session.commit()

            flash('Proses peminjaman alat selesai!','success')
            return redirect(url_for('pinjam.index'))

    return redirect(url_for('user.login'))


@mod.route('/pinjam/selesai/<int:id>', methods=['GET','POST'])
def selesai(id):
    if "username" in session:
        pinjam = Peminjam_alat.query.get_or_404(id)
        if pinjam:
            pinjam.status ='dikembalikan'
            pinjam.tanggal_selesai = datetime.now()

            aksi = f"Pengembalian alat: {pinjam.id} simpan"
            log = Loguser(session['username'], aksi)
            db.session.add(log)
            db.session.commit()

            flash('Proses pengembalian alat selesai!','success')
            return redirect(url_for('pinjam.index'))
    return redirect(url_for('user.login'))


@mod.route('/pinjam/pengembalian/<int:id>')
def pengembalian(id):
    if "username" in session:
        data = {
            'title' : 'Pengembalian Alat',
            'header' :'Pengembalian Alat'
        }
        peminjam = Peminjam_alat.query.get(id)
        lihat = Log_pinjam.query.filter_by(id_peminjam=id).all()
        
        return render_template('pinjam/pengembalian.html', data=data, lihat=lihat, peminjam=peminjam)
    return redirect(url_for('user.login'))


@mod.route('/pinjam/note/<int:id>', methods=['GET','POST'])
def note(id):
    cari = Log_pinjam.query.get_or_404(id)
    if cari:
        if request.method == "POST":
            note = request.form['note']
            cari.note = note
            db.session.commit()
            return redirect(url_for('pinjam.pengembalian', id=cari.id_peminjam))


@mod.route('/pinjam/beban_kerja_alat/<int:id>', methods=['GET','POST'])
def beban_kerja(id):
    cari = Log_pinjam.query.get_or_404(id)
    if cari:
        if request.method == "POST" :
            beban_kerja = request.form['beban']
            cari.beban_kerja = beban_kerja
            db.session.commit()
            return redirect(url_for('pinjam.daftar', id = cari.id_peminjam))
    

aplikasi/user/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from sqlalchemy import exc
from .forms import Register, Edit_user
from aplikasi import db, bcrypt
from aplikasi.models import Users


mod = Blueprint('user',__name__, template_folder='templates')


@mod.route('/login', methods=['GET','POST'])
def login():
    if request.method == "POST":
        user = request.form['username']
        paswd = request.form['password']
        
        u = Users.query.filter_by(username=user).first()
        if u:
            if bcrypt.check_password_hash(u.password, paswd):
                session['username'] = user
                session['nm_lengkap'] = u.nm_lengkap
                session['level'] = u.level
                return redirect(url_for('main.index'))
            else:
                flash('Password anda salah!!', 'warning')
                return redirect(url_for('user.login'))

        flash('Username tidak ditemukan!!','info')
        return redirect(url_for('user.login'))
        
    return render_template('user/login.html')


@mod.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('user.login'))


@mod.route('/user/list')
def list():
    data = {
        'title':'Users list',
        'header':'Users list',
        'user' : Users.query.all()
    }

    return render_template('user/index.html', data=data)


@mod.route('/user/add', methods=['GET','POST'])
def reg():
    data = {
        'title':'Add user',
        'header':'Add user'
    }

    form = Register()
    if form.validate_on_submit():
        try:
            username = form.username.data
            pw_hash = bcrypt.generate_password_hash(form.password.data)
            email = form.email.data
            nm_lengkap = form.nm_lengkap.data
            level = form.level.data
            pwdnew = pw_hash.decode("utf-8", "ignore")

            user = Users(username, pwdnew, email, nm_lengkap,level, "")
            db.session.add(user)
            db.session.commit()
            flash('User baru berhasil dibuat!!','success')
            return redirect(url_for('user.list')) 
        except exc.IntegrityError:
            db.session.rollback()
            flash('Maaf, data sudah ada !!!. Silahkan gunakan yang lain.','warning')
            return redirect(url_for('user.reg'))        

    return render_template('user/register.html', data=data, form=form)

@mod.route('/user/edit/<int:id>', methods=['GET','POST'])
def edit(id):
    data = {
        'title':'Edit user',
        'header':'Edit user'
    }
    user = Users.query.get_or_404(id)

    if user:
        form = Edit_user()
        if form.validate_on_submit():
            user.username = form.username.data
            user.email = form.email.data
            user.nm_lengkap = form.nm_lengkap.data
            user.level = form.level.data
            
            db.session.commit()

            flash("User berhasil diupdate!","info")
            return redirect(url_for('user.list'))
        
        form.username.data = user.username
        form.email.data = user.email
        form.nm_lengkap.data = user.nm_lengkap
        form.level.data = user.level

        return render_template('user/edit.html', data=data, form=form)

    
@mod.route('/user/hapus/<int:id>', methods=['GET','POST'])
def hapus(id):
    user = Users.query.get_or_404(id)
    if user:
        db.session.delete(user)
        db.session.commit()

        flash("Data berhasil dihapus!!","info")
        return redirect(url_for('user.list'))

aplikasi/templates/pinjam/index copy.html
{% extends 'pinjam/base.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ data.header }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
    </div>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}      
      {% for category,message in messages %}
      <script>
        swal("Notifikasi", "{{message}}", "{{ category }}");
      </script>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div class="table-responsive">
    <table id="working" class="table table-striped table-sm">
      <thead>
        <tr>
          <th>No</th>          
          <th>Nama Peminjam</th>
          <th>Petugas Catat</th>        
          <th>Tanggal</th>
          <th>Tujuan</th>
          <th>Tanggal Berangkat</th>
          <th>Tanggal Kembali</th>
          <th>Status</th>
          <th>Keterangan</th>
          <th>Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for d in data.pinjam %}       
        <tr>
          <td>{{ loop.index }}</td>          
          <td>{{ d.peminjam_alat }}</td>
          <td>{{ d.petugas_catat }}</td>      
          <td>{{ d.tanggal.strftime("%d-%m-%Y") }} </td>
          <td>{{ d.tujuan }}</td>
          <td>{{ d.tanggal_berangkat.strftime("%d-%m-%Y") }} </td>
          <td>{{ d.tanggal_kembali.strftime("%d-%m-%Y") }} </td>
          {% if d.status =='Pinjam' %}
            <td style="color: orange;"><strong>{{ d.status }}</strong></td>
          {% endif %}         
          
          <td>{{ d.Keterangan }}</td>
          <td><a href="{{ url_for('pinjam.lihat_data') }}" title="Lihat Data"><span data-feather="zoom-in"></span></a> | <a href="" data-toggle="modal" data-target="#hapus{{ d.id }}" title="Hapus"><span data-feather="trash-2"></span></a></td>
        </tr>

        <!-- Modal Konfirmasi Hapus-->
        <div class="modal fade" id="hapus{{ d.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Yakin akan menghapus data {{ d.peminjam }}?
              </div>
              <div class="modal-footer">
                <form action="{{ url_for('pinjam.hapus',id=d.id) }}" method="post">
                  <button type="submit" class="btn btn-primary">Iya</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                </form>                 
              </div>
            </div>
          </div>
        </div>        
        {% endfor %}       
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

aplikasi/templates/pinjam/input_alat.html
{% extends 'pinjam/base.html' %}

{% block content %}

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ data.header }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
    </div>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}      
        {% for category,message in messages %}
        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <!-- <strong>Title</strong> --> {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    {% endwith %}

    <!-- menampilkan data peminjam -->
    <div class="row">
        <div class="col-sm">
            <div class="form-group row">
                <label for="peminjam_alat" class="col-sm-2 col-form-label">Peminjam alat</label>
                <div class="col-sm-6">
                    <input type="text" readonly class="form-control" id="peminjam_alat" value="{{ data.query.peminjam_alat}}">
                </div>
            </div>
            <div class="form-group row">
                <label for="tanggal" class="col-sm-2 col-form-label">Tanggal Peminjaman</label>
                <div class="col-sm-6">
                    <input type="text" readonly class="form-control" id="tanggal" value="{{ data.query.tanggal.strftime('%d-%m-%Y') }}">
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="form-group row">
                <label for="tujuan" class="col-sm-2 col-form-label">Tujuan</label>
                <div class="col-sm-6">
                    <input type="text" readonly class="form-control" id="tujuan" value="{{ data.query.tujuan }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="petugas_catat" class="col-sm-2 col-form-label">Petugas Catat</label>
                <div class="col-sm-6">
                    <input type="text" readonly class="form-control" id="tujuan" value="{{ data.query.petugas_catat }}">
                </div>
            </div>
        </div>
        <!-- <input type="hidden" value="{{ data.query.id }}" id="getid"> -->
    </div>
    <!-- end data peminjaman -->

    <div class="row">        
        <div class="col-sm-12">            
            <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModal">Tambahkan Alat</button>

            <!-- Modal Add Kode Alat-->            
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Input Kode Alat</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <form method="post" novalidate>
                {{ form.hidden_tag() }}

                <div class="modal-body">                    

                    <div class="form-group">
                        {{ form.kd_alat.label(class="col-sm-6 col-form-label") }}
                        {% if form.kd_alat.errors %}
                          <div class="col-sm-10 has-error">
                            {{ form.kd_alat(class="form-control") }}                                        
                            {% for error in form.kd_alat.errors  %}
                                <span class="control-label">{{ error }}</span>
                            {% endfor %}
                          </div>
                        {% else %}
                        <div class="col-sm-10">
                          {{ form.kd_alat(class="form-control") }}
                        </div>
                        {% endif %}
                    </div>                    
                    
                </div>
                <div class="modal-footer">
                    {{ form.simpan(class="btn btn-primary") }}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Keluar</button>
                </div>
            </form>
                </div>
            </div>
            </div>
            <!-- end modal -->
            </div>
        </div>
        
    <br>
    <!-- table -->
    <div class="table-responsive">
        <table class="table table-striped table-sm" id="working">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Kode Alat</th>
                    <th>Nama Alat</th>
                    <th>Merk Alat</th>
                    <th>Serial Number</th>
                    <th>Tgl. Kalibrasi</th>
                    <th>Beban Kerja (Alat)</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                {% for i in detail %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ i.alat.kd_alat }}</td>
                        <td>{{ i.alat.nm_alat }}</td>
                        <td>{{ i.alat.merk }}</td>
                        <td>{{ i.alat.no_seri }}</td>
                        <td>{{ i.alat.tgl_kalibrasi }}</td>
                        <th>
                            {% if i.beban_kerja=="" or i.beban_kerja==None %}
                                <button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#beban{{ i.id }}"><span data-feather="edit"></span> Update</button>
                                <!-- <a href="#" data-toggle="modal" data-target="#beban{{ i.id }}" title="Input Beban Kerja Alat"><span data-feather="plus"></span></a> -->
                            {% else %}
                                {{ i.beban_kerja }}
                            {% endif %}                           
                            
                        </th>
                        <td>
                            <button class="btn btn-sm btn-outline-secondary" data-toggle="modal" data-target="#hapus{{ i.id }}" title="Hapus"><span data-feather="trash-2"></span> Hapus</button>
                            <!-- <a href="#" data-toggle="modal" data-target="#hapus{{ i.id }}" title="Hapus"><span data-feather="trash-2"></span></a> -->
                        </td>
                    </tr>

                    <!-- Modal Konfirmasi Hapus-->
                    <div class="modal fade" id="hapus{{ i.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                            <strong>Anda yakin akan menghapus {{i.alat.nm_alat}} : ?</strong>
                            </div>
                            <div class="modal-footer">
                            <form action="{{ url_for('pinjam.hapus_alat',id=i.id) }}" method="post">
                                <button type="submit" class="btn btn-primary">Iya</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                            </form>                 
                            </div>
                        </div>
                        </div>
                    </div>
                    <!-- end modal hapus -->

                    <!-- Modal Update Beban Kerja-->
                    <div class="modal fade" id="beban{{ i.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Beban Kerja Alat</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <form action="{{ url_for('pinjam.beban_kerja', id=i.id)}}" method="post">
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label for="" class="col-sm-6 col-form-label">Nama Alat</label>
                                        <input type="text" class="form-control" value="{{ i.alat.nm_alat }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="" class="col-sm-6 col-form-label">Nomor seri</label>
                                        <input type="text" class="form-control" value="{{ i.alat.no_seri }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="" class="col-sm-6 col-form-label">Pemakaian</label>
                                        <input type="text" class="form-control" value="{{ i.peminjam.tujuan }}" readonly>
                                    </div>
                                    <div class="form-group">
                                        <label for="" class="col-sm-6 col-form-label">Beban Kerja Alat</label>
                                        <input type="text" class="form-control" name="beban">
                                    </div>
                                </div>
                                <div class="modal-footer">                            
                                    <button type="submit" class="btn btn-primary">Simpan</button>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                </form>                
                                </div>
                        </div>
                        </div>
                    </div>
                    <!-- end modal beban -->

                {% endfor %}  
            </tbody>
        </table>
    </div>        
    <!-- end Table -->

    <!-- tombol simpan untuk menyelesaikan proses -->
    {% if detail %}
    <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#simpanModal" >Simpan Proses</button>
    {% endif %}
    <!-- Modal Add Kode Alat-->            
    <div class="modal fade" id="simpanModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Konfirmasi</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">                
                <p>Apakah proses sudah selesai ?.</p>
            </div>
            <div class="modal-footer">
                <form action="{{ url_for('pinjam.simpan_proses',id=data.query.id) }}" method="post">
                    <button type="submit" class="btn btn-primary">Iya</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                </form>
            </div>
            </div>
        </div>
        </div>
        <!-- end modal -->
</main>
{% endblock %}

aplikasi/templates/pinjam/response.html
<h3>Daftar alat yang dipinjam</h3>
<table class="table table-hover">
    <thead>
        <tr>
            <th>No</th>
            <th>Nama Alat</th>
            <th>Merk</th>
            <th>Tipe</th>
            <th>Serial Number</th>
            <th>Proses</th>
        </tr>
    </thead>
    <tbody>
        {% for i in detail %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ i.alat.nm_alat }}</td>
            <td>{{ i.alat.merk }}</td>
            <td>{{ i.alat.tipe }}</td>
            <td>{{ i.alat.no_seri }}</td>
            <td><a href="">Hapus</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>