aplikasi/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, SelectField
from wtforms.validators import DataRequired, EqualTo, Email, Length


class Register(FlaskForm):
    username =  StringField('Username', validators=[DataRequired(), Length(min=5, max=20)])
    password =  PasswordField('Password', validators=[DataRequired(), EqualTo('confirm'), Length(min=6, max=50)])
    confirm = PasswordField('Repeat Password')
    email = StringField('Email', validators=[DataRequired(), Email()])
    nm_lengkap = StringField('Nama lengkap', validators=[DataRequired(), Length(min=6, max=30)])
    level =  SelectField('Level',
        choices=[('none','...Pilih..'),('admin','Admin'),('pengguna','Pengguna')])  
    submit = SubmitField('Submit')


class Edit_user(FlaskForm):
    username =  StringField('Username', validators=[DataRequired(), Length(min=5, max=20)])    
    email = StringField('Email', validators=[DataRequired(), Email()])
    nm_lengkap = StringField('Nama lengkap', validators=[DataRequired(), Length(min=6, max=30)])
    level =  SelectField('Level',
        choices=[('none','...Pilih..'),('admin','Admin'),('pengguna','Pengguna')])  
    submit = SubmitField('Submit')

aplikasi/user/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from sqlalchemy import exc
from .forms import Register, Edit_user
from aplikasi import db, bcrypt
from aplikasi.models import Users


mod = Blueprint('user',__name__, template_folder='templates')


@mod.route('/login', methods=['GET','POST'])
def login():
    if request.method == "POST":
        user = request.form['username']
        paswd = request.form['password']
        
        u = Users.query.filter_by(username=user).first()
        if u:
            if bcrypt.check_password_hash(u.password, paswd):
                session['username'] = user
                session['nm_lengkap'] = u.nm_lengkap
                session['level'] = u.level
                return redirect(url_for('main.index'))
            else:
                flash('Password anda salah!!', 'warning')
                return redirect(url_for('user.login'))

        flash('Username tidak ditemukan!!','info')
        return redirect(url_for('user.login'))
        
    return render_template('user/login.html')


@mod.route('/logout')
def logout():
    session.pop('username', None)
    return redirect(url_for('user.login'))


@mod.route('/user/list')
def list():
    data = {
        'title':'Users list',
        'header':'Users list',
        'user' : Users.query.all()
    }

    return render_template('user/index.html', data=data)


@mod.route('/user/add', methods=['GET','POST'])
def reg():
    data = {
        'title':'Add user',
        'header':'Add user'
    }

    form = Register()
    if form.validate_on_submit():
        try:
            username = form.username.data
            pw_hash = bcrypt.generate_password_hash(form.password.data)
            email = form.email.data
            nm_lengkap = form.nm_lengkap.data
            level = form.level.data
            pwdnew = pw_hash.decode("utf-8", "ignore")

            user = Users(username, pwdnew, email, nm_lengkap,level, "")
            db.session.add(user)
            db.session.commit()
            flash('User baru berhasil dibuat!!','success')
            return redirect(url_for('user.list')) 
        except exc.IntegrityError:
            db.session.rollback()
            flash('Maaf, data sudah ada !!!. Silahkan gunakan yang lain.','warning')
            return redirect(url_for('user.reg'))        

    return render_template('user/register.html', data=data, form=form)

@mod.route('/user/edit/<int:id>', methods=['GET','POST'])
def edit(id):
    data = {
        'title':'Edit user',
        'header':'Edit user'
    }
    user = Users.query.get_or_404(id)

    if user:
        form = Edit_user()
        if form.validate_on_submit():
            user.username = form.username.data
            user.email = form.email.data
            user.nm_lengkap = form.nm_lengkap.data
            user.level = form.level.data
            
            db.session.commit()

            flash("User berhasil diupdate!","info")
            return redirect(url_for('user.list'))
        
        form.username.data = user.username
        form.email.data = user.email
        form.nm_lengkap.data = user.nm_lengkap
        form.level.data = user.level

        return render_template('user/edit.html', data=data, form=form)

    
@mod.route('/user/hapus/<int:id>', methods=['GET','POST'])
def hapus(id):
    user = Users.query.get_or_404(id)
    if user:
        db.session.delete(user)
        db.session.commit()

        flash("Data berhasil dihapus!!","info")
        return redirect(url_for('user.list'))

aplikasi/templates/user/base_user.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>{{ data.title }} · SIMUPF</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Bootstrap dataTables -->
    <link href="{{ url_for('static', filename='/dataTables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">

    <!-- sweetalert -->
    <script src="{{ url_for('static', filename='sweetalert.min.js') }}"></script>

  </head>
  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="{{ url_for('main.dashboard') }}"><span><img src="{{ url_for('static', filename='favicon.png') }}" alt=""></span> UPFK Palembang</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.dashboard') }}">
              <span data-feather="skip-back"></span>
              Kembali 
              <!-- <span class="sr-only">(current)</span> -->
            </a>
          </li>
        </ul>
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>User Management</span>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.list') }}">
              <span data-feather="users"></span>
              Users List
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.reg') }}">
              <span data-feather="user"></span>
              Add User
            </a>
          </li>
        </ul>
      </div>
    </nav>

    {% block content %}
    {% endblock %}
  </div>
</div>
      <script src="{{ url_for('static', filename='jquery-3.5.1.slim.min.js') }}"></script>
      <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
      <script src="{{ url_for('static', filename='/dist/js/bootstrap.bundle.min.js') }}"></script>
      <script src="{{ url_for('static', filename='feather.min.js') }}"></script>
      <script src="{{ url_for('static', filename='Chart.min.js') }}"></script>
      <script src="{{ url_for('static', filename='dashboard.js') }}"></script>
      <script src="{{ url_for('static', filename='/dataTables/jquery.dataTables.min.js') }}"></script>
      <script src="{{ url_for('static', filename='/dataTables/dataTables.bootstrap4.min.js') }}"></script>
      <script>
        $(document).ready( function () {
            $('#table_id').DataTable();
        } );
      </script>

  </body>
</html>

aplikasi/templates/user/edit.html
{% extends 'user/base_user.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ data.header }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
    </div>
  </div>

  
  <form method="POST" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-group row">
      {{ form.username.label(class="col-sm-2 col-form-label") }}
      {% if form.username.errors %}
        <div class="col-sm-10 has-error">
          {{ form.username(class="form-control") }}                                        
          {% for error in form.username.errors  %}
              <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.username(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      {{ form.email.label(class="col-sm-2 col-form-label") }}
      {% if form.email.errors %}
        <div class="col-sm-10">
          {{ form.email(class="form-control") }}                                        
          {% for error in form.email.errors  %}
            <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.email(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      {{ form.nm_lengkap.label(class="col-sm-2 col-form-label") }}
      {% if form.nm_lengkap.errors %}
        <div class="col-sm-10 has-error">
          {{ form.nm_lengkap(class="form-control") }}                                        
          {% for error in form.nm_lengkap.errors  %}
              <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.nm_lengkap(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      {{ form.level.label(class="col-sm-2 col-form-label") }}
      {% if form.level.errors %}
        <div class="col-sm-10 has-error">
          {{ form.level(class="form-control") }}                                        
          {% for error in form.level.errors  %}
              <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.level(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </div>
  </form>
</main>
{% endblock %}

aplikasi/templates/user/index.html
{% extends 'user/base_user.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ data.header }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
    </div>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}      
      {% for category,message in messages %}
      <script>
        swal("Notifikasi", "{{message}}", "{{ category }}");
      </script>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <div class="table-responsive">
    <table id="working" class="table table-striped table-sm">
      <thead>
        <tr>
          <th>No</th>
          <th>Username</th>
          <th>Nama Lengkap</th>
          <th>Email</th>
          <th>Level</th>
          <th>Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for d in data.user %}
        <tr>
          <td>{{ loop.index }}</td>
          <td>{{ d.username }}</td>
          <td>{{ d.nm_lengkap }}</td>
          <td>{{ d.email }}</td>
          <td>{{ d.level }}</td>
          <td><a href="{{ url_for('user.edit',id=d.id) }}" title="Edit"><span data-feather="edit"></span></a> | <a href="" data-toggle="modal" data-target="#hapus{{ d.id }}" title="Hapus"><span data-feather="trash-2"></span></a></td>
        </tr>

        <!-- Modal Konfirmasi Hapus-->
        <div class="modal fade" id="hapus{{ d.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Hapus Data</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <strong>Yakin akan menghapus {{ d.username }}?</strong>
              </div>
              <div class="modal-footer">
                <form action="{{ url_for('user.hapus',id=d.id) }}" method="post">
                  <button type="submit" class="btn btn-primary">Iya</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
                </form>                 
              </div>
            </div>
          </div>
        </div>        
        {% endfor %}       
      </tbody>
    </table>
  </div>
</main>
{% endblock %}

aplikasi/templates/user/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Login · SIMUPF</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='/dist/css/bootstrap.min.css') }}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='signin.css') }} " rel="stylesheet">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
    <!-- sweetalert -->
    <script src="{{ url_for('static', filename='sweetalert.min.js') }}"></script>
    
  </head>
  <body class="text-center">

  <form class="form-signin" method="POST">
    <img class="mb-4" src="{{ url_for('static', filename='kemkes.png') }}" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Login - SIMUPF</h1>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}      
      {% for category,message in messages %}
      <script>
        swal("Notifikasi", "{{message}}", "{{ category }}");
      </script>
      {% endfor %}
    {% endif %}
  {% endwith %}

    <label for="inputUsername" class="sr-only">Username</label>
    <input type="text" id="inputUsername" class="form-control" name="username" placeholder="Username" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" name="password" placeholder="Password" required>
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
    <p class="mt-5 mb-3 text-muted">&copy; IT UPF-PFK 2019-2020</p>
</form>
</body>
</html>

aplikasi/templates/user/register.html
{% extends 'user/base_user.html' %}

{% block content %}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">{{ data.header }}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
        <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
    </div>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}      
      {% for category,message in messages %}
      <div class="alert alert-{{ category }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{message}}
      </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  <form method="POST" novalidate>
    {{ form.hidden_tag() }}
    <div class="form-group row">
      {{ form.username.label(class="col-sm-2 col-form-label") }}
      {% if form.username.errors %}
        <div class="col-sm-10 has-error">
          {{ form.username(class="form-control") }}                                        
          {% for error in form.username.errors  %}
              <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.username(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      {{ form.password.label(class="col-sm-2 col-form-label") }}
      {% if form.password.errors %}
        <div class="col-sm-10 has-error">
          {{ form.password(class="form-control") }}                                        
          {% for error in form.password.errors  %}
              <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.password(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      {{ form.confirm.label(class="col-sm-2 col-form-label") }}
      {% if form.confirm.errors %}
        <div class="col-sm-10 has-error">
          {{ form.confirm(class="form-control") }}                                        
          {% for error in form.confirm.errors  %}
              <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.confirm(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      {{ form.email.label(class="col-sm-2 col-form-label") }}
      {% if form.email.errors %}
        <div class="col-sm-10">
          {{ form.email(class="form-control") }}                                        
          {% for error in form.email.errors  %}
            <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.email(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      {{ form.nm_lengkap.label(class="col-sm-2 col-form-label") }}
      {% if form.nm_lengkap.errors %}
        <div class="col-sm-10 has-error">
          {{ form.nm_lengkap(class="form-control") }}                                        
          {% for error in form.nm_lengkap.errors  %}
              <span class="control-label">{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
      <div class="col-sm-10">
        {{ form.nm_lengkap(class="form-control") }}
      </div>
      {% endif %}
    </div>

    <div class="form-group row">
      <div class="col-sm-10">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </div>
  </form>
</main>
{% endblock %}